#cloud-config

package_upgrade: true
packages:
  - zsh
  - tmux
  - curl
  - wget
  - htop
  - iperf
  - vim

runcmd:
  - echo "You can add more commands here"

write_files:
  - encoding: b64
    path: /var/lib/rancher/k3s/server/manifests/aws-ccm-ds.yaml
    permission: "0644"
    content: ${aws_ccm_ds}
  - encoding: b64
    path: /var/lib/rancher/k3s/server/manifests/aws-rbac.yaml
    permission: "0644"
    content: ${aws_rbac}
